# Generated by Django 3.2 on 2021-04-17 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_cliente_clienteorigem_pagamentos_pedido_pedidoorigem_produto_produtopedito'), ('core', '0003_auto_20210417_1302'), ('core', '0004_auto_20210417_1336'), ('core', '0005_auto_20210417_1337'), ('core', '0006_auto_20210417_1343'), ('core', '0007_auto_20210417_1358'), ('core', '0008_auto_20210417_1409'), ('core', '0009_rename_cliente_origem_pedidoorigem_cliente_id'), ('core', '0010_rename_produtopedito_produtopedido')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('texto', models.TextField(max_length=400, verbose_name='Texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteOrigem',
            fields=[
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('bairro', models.CharField(max_length=255, null=True, verbose_name='Bairro')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('cliente_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id do Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('SKU', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=2, verbose_name='Tamanho')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('data_envio', models.DateTimeField(verbose_name='Data do Envio')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('fonte_mkt', models.CharField(max_length=20, verbose_name='Fonte de Marketing')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentários')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NF', models.CharField(max_length=255, verbose_name='Nota Fiscal')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('meio_pagamento', models.CharField(max_length=20, verbose_name='Meio de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor do Pagamento')),
                ('pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoOrigem',
            fields=[
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('data_envio', models.DateTimeField(verbose_name='Data do Envio')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('fonte_mkt', models.CharField(max_length=20, verbose_name='Fonte de Marketing')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentários')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('NF', models.CharField(max_length=255, verbose_name='Nota Fiscal')),
                ('meio_pagamento', models.CharField(max_length=20, verbose_name='Meio de Pagamento')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço Unitario')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=2, verbose_name='Tamanho')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('cliente_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clienteorigem')),
                ('SKU_origem', models.CharField(max_length=50, null=True, verbose_name='SKU')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor')),
                ('pedido_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('pedido_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço Unitátio')),
                ('produto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
