# Generated by Django 3.2 on 2021-04-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(verbose_name='Id do Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(verbose_name='Id do Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50, verbose_name='SKU')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=2, verbose_name='Tamanho')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(verbose_name='Id do Pedido')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço Unitátio')),
                ('produto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(verbose_name='Id do Pedido')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('data_envio', models.DateTimeField(verbose_name='Data do Envio')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('fonte_mkt', models.CharField(max_length=20, verbose_name='Fonte de Marketing')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentários')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('NF', models.CharField(max_length=255, verbose_name='Nota Fiscal')),
                ('meio_pagamento', models.CharField(max_length=20, verbose_name='Meio de Pagamento')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço Unitátio')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=2, verbose_name='Tamanho')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('cliente_origem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clienteorigem')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(verbose_name='Id do Pedido')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('data_envio', models.DateTimeField(verbose_name='Data do Envio')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('fonte_mkt', models.CharField(max_length=20, verbose_name='Fonte de Marketing')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentários')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NF', models.CharField(max_length=255, verbose_name='Nota Fiscal')),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('meio_pagamento', models.CharField(max_length=20, verbose_name='Meio de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor do Pagamento')),
                ('pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
    ]
