# Generated by Django 3.2 on 2021-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_clienteorigem_pagamentos_pedido_pedidoorigem_produto_produtopedito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoorigem',
            name='SKU_origem',
            field=models.CharField(default=1, max_length=50, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='pedidoorigem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pedidoorigem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço Unitario'),
        ),
    ]
