# Generated by Django 3.2 on 2021-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210417_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteorigem',
            name='bairro',
            field=models.CharField(max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clienteorigem',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
