# Generated by Django 3.2 on 2021-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210417_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoorigem',
            name='SKU_origem',
            field=models.CharField(max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='pedidoorigem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Valor'),
        ),
    ]
