# Generated by Django 3.2 on 2021-04-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210417_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteorigem',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='pedidoorigem',
            name='pedido_id',
        ),
    ]
