# Generated by Django 3.2 on 2021-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210417_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clienteorigem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedidoorigem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produtopedito',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Cliente'),
        ),
        migrations.AlterField(
            model_name='clienteorigem',
            name='cliente_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoorigem',
            name='pedido_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoorigem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='SKU',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='produtopedito',
            name='pedido_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Pedido'),
        ),
    ]
