# Generated by Django 3.2 on 2021-04-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210417_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoorigem',
            old_name='cliente_origem',
            new_name='cliente_id',
        ),
    ]
