# Generated by Django 3.2 on 2021-04-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cliente_origem_pedidoorigem_cliente_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoPedito',
            new_name='ProdutoPedido',
        ),
    ]
